Scratch

In [1]:
test = [
            dict( n=6, val= 5, moe=1, newBlockP1=0.8, newBlockP2=0.2),
            dict( n=10, val= 15, moe=2, newBlockP1=0.3, newBlockP2=0.7)
        ]




In [2]:
## number of people
import pandas

df= pandas.DataFrame(test)
df

moe   n  newBlockP1  newBlockP2  val
0    1   6         0.8         0.2    5
1    2  10         0.3         0.7   15

In [16]:
## number of people

## deterministic

df[['newBlockP1','newBlockP2']]

newBlockP1  newBlockP2
0         0.8         0.2
1         0.3         0.7

In [3]:
nam=list(df.columns.values)
nam

['moe', 'n', 'newBlockP1', 'newBlockP2', 'val']

In [4]:
nam.remove("moe")
nam.remove('n')
nam.remove('val')
nam

['newBlockP1', 'newBlockP2']

In [89]:

for i in range(df.shape[0]):
    print(df['n'][i]*df[i:(i+1)][nam])
   # how do I store these, then want to sum over columns 

   newBlockP1  newBlockP2
0         4.8         1.2
   newBlockP1  newBlockP2
1         3.0         7.0


In [9]:
## with moe
import numpy
for i in range(df.shape[0]):
    se = df['n'][i] / 1.645 ## convert moe to se
    new_n = round(numpy.random.normal(df['n'][i], se))
    ## use moe to introduce randomness into number in bin
    new_n = int(new_n) ## clean it up
    print(new_n*df[i:(i+1)][nam])

   # how do I store these, then want to sum over columns 

   newBlockP1  newBlockP2
0         2.4         0.6
   newBlockP1  newBlockP2
1         4.5        10.5


In [7]:
## mean
## go through by columns
## deterministic

for i in nam:
    print(sum(df['n']*df[i]*df['val'])/sum(df['n']*df[i]))

8.846153846153845
13.536585365853659


In [13]:
## mean
## go through by columns
## random

sim_n = []
for i in range(df.shape[0]):
    se = df['n'][i] / 1.645 ## convert moe to se
    new_n = round(numpy.random.normal(df['n'][i], se))
    ## use moe to introduce randomness into number in bin
    new_n = int(new_n) ## clean it up
    sim_n.append(new_n)

for i in nam:
    print(sum(new_n*df[i]*df['val'])/sum(new_n*df[i]))

7.7272727272727275
12.777777777777779


In [ ]:
## median
## deterministic



In [153]:
import math
household_income_2013_acs5 = [
            dict(min=math.nan, max=9999, n=6, moe=1),
            dict(min=10000, max=14999, n=1, moe=1),
            dict(min=15000, max=19999, n=8, moe=1),
            dict(min=20000, max=24999, n=7, moe=1),
            dict(min=25000, max=29999, n=2, moe=1),
            dict(min=30000, max=34999, n=900, moe=8),
            dict(min=35000, max=39999, n=7, moe=1),
            dict(min=40000, max=44999, n=4, moe=1),
            dict(min=45000, max=49999, n=8, moe=1),
            dict(min=50000, max=59999, n=6, moe=1),
            dict(min=60000, max=74999, n=7, moe=1),
            dict(min=75000, max=99999, n=2, moe=0.25),
            dict(min=100000, max=124999, n=7, moe=1),
            dict(min=125000, max=149999, n=10, moe=1),
            dict(min=150000, max=199999, n=8, moe=1),
            dict(min=200000, max=math.nan, n=18, moe=10)
        ]

household_income_la_2013_acs1 = [
      dict(min=0, max=9999, n=1382, moe = 50),
      dict(min=10000, max=14999, n=2377, moe = 50),
      dict(min=15000, max=19999, n=1332, moe = 50),
      dict(min=20000, max=24999, n=3129, moe = 50),
      dict(min=25000, max=29999, n=1927, moe = 50),
      dict(min=30000, max=34999, n=1825, moe = 50),
      dict(min=35000, max=39999, n=1567, moe = 50),
      dict(min=40000, max=44999, n=1996, moe = 50),
      dict(min=45000, max=49999, n=1757, moe = 50),
      dict(min=50000, max=59999, n=3523, moe = 50),
      dict(min=60000, max=74999, n=4360, moe = 50),
      dict(min=75000, max=99999, n=6424, moe = 50),
      dict(min=100000, max=124999, n=5257, moe = 50),
      dict(min=125000, max=149999, n=3485, moe = 50),
      dict(min=150000, max=199999, n=2926, moe = 50),
      dict(min=200000, max=500000, n=4215, moe = 50)
  ]


test_input = [household_income_2013_acs5,household_income_la_2013_acs1]

makeup_1 = [0.8, 0.2]
makeup_2 =  [0.3, 0.7]

makeup_input = [makeup_1, makeup_2]


In [154]:
def disaggregate_sum(data_list, makeup, deterministic = True, simulations=50):
## replace some of this with dot products?
    if deterministic:
        results = []
        grand_total = []
        for i in range(len(data_list)):
            total = []
            for j in range(0, len(data_list[i])):
                total.append(data_list[i][j]['n'])
            grand_total.append(sum(total))
            results.append([grand_total[i]*z for z in makeup[i]]) ## store this row
        rr = numpy.vstack(results)
        est = numpy.apply_along_axis(sum, 0, rr) 
        return est, None
    else:
        simulation_results = []
        for s in range(simulations):
            results = []
            grand_total = []
            for i in range(len(data_list)):
                total = []
                for j in range(len(data_list[i])):
                    se = data_list[i][j]['moe'] / 1.645 ## convert moe to se
                    new_n = round(numpy.random.normal(data_list[i][j]['n'], se))
                    ## use moe to introduce randomness into number in bin
                    new_n = int(new_n) ## clean it up
                    total.append(new_n)
                grand_total.append(sum(total))
                results.append([grand_total[i]*z for z in makeup[i]]) ## store this row
            rr = numpy.vstack(results)
            simulation_results.append(numpy.apply_along_axis(sum, 0, rr)) 
        ss = numpy.vstack(simulation_results)
        est = numpy.apply_along_axis(numpy.mean, 0, ss)
        t1 = numpy.apply_along_axis(numpy.quantile, axis=0, arr =ss, q=0.95) - est
        t2 = est - numpy.apply_along_axis(numpy.quantile, axis=0, arr = ss, q=0.05)
        margin_of_error = numpy.amax(numpy.column_stack((t1,t2)), 1)
        return est, margin_of_error

In [151]:
disaggregate_sum(test_input, makeup_input, deterministic = True, simulations=50)

(array([15045.4, 33437.6]), None)

In [156]:
test = disaggregate_sum(test_input, makeup_input, deterministic = True, simulations=50)
test[0]

array([15045.4, 33437.6])

In [155]:
disaggregate_sum(test_input, makeup_input, deterministic = False, simulations=50)

(array([15045.006, 33430.114]), array([ 70.876, 167.684]))

In [190]:
def disaggregate_mean(data_list, makeup, deterministic = True, simulations=50):
    # can we call disaggregate_sum in here
    if deterministic:
        denom = disaggregate_sum(data_list, makeup, deterministic = True, simulations=50)[0]
        results = []
        grand_total = []
        for i in range(len(data_list)):
            total = []
            for j in range(0, len(data_list[i])):
                total.append(data_list[i][j]['n'] * data_list[i][j]['val'])
            grand_total.append(sum(total))
            results.append([grand_total[i]*z for z in makeup[i]]) ## store this row
        rr = numpy.vstack(results)
        rr2 = numpy.apply_along_axis(sum, 0, rr) 
        est = numpy.divide(rr2, denom)
        return est, None
    else:
        ## have to redo simulation can't just use sum call
        simulation_results = []
        simulation_results_v = []
        for s in range(simulations):
            results = []
            results_v = []
            grand_total = []
            grand_total_v = []
            for i in range(len(data_list)):
                total = []
                total_v = []
                for j in range(len(data_list[i])):
                    se = data_list[i][j]['moe'] / 1.645 ## convert moe to se
                    new_n = round(numpy.random.normal(data_list[i][j]['n'], se))
                    ## use moe to introduce randomness into number in bin
                    new_n = int(new_n) ## clean it up
                    total.append(new_n)
                    total_v.append(new_n * data_list[i][j]['val'])
                grand_total.append(sum(total))
                grand_total_v.append(sum(total_v))
                results.append([grand_total[i]*z for z in makeup[i]]) 
                results_v.append([grand_total_v[i]*z for z in makeup[i]])
            rr = numpy.vstack(results)
            rr_v = numpy.vstack(results_v)
            simulation_results.append(numpy.apply_along_axis(sum, 0, rr)) 
            simulation_results_v.append(numpy.apply_along_axis(sum, 0, rr_v))
        ss = numpy.vstack(simulation_results)
        ss_v = numpy.vstack(simulation_results_v)
        ## divide then do this
        ssd = numpy.divide(ss_v, ss)
        est = numpy.apply_along_axis(numpy.mean, 0, ssd)
        t1 = numpy.apply_along_axis(numpy.quantile, axis=0, arr =ssd, q=0.95) - est
        t2 = est - numpy.apply_along_axis(numpy.quantile, axis=0, arr = ssd, q=0.05)
        margin_of_error = numpy.amax(numpy.column_stack((t1,t2)), 1)
        return est, margin_of_error


In [165]:
household_income_2013_acs5 = [
            dict(min=math.nan, val=9999, n=6, moe=1),
            dict(min=10000, val=14999, n=1, moe=1),
            dict(min=15000, val=19999, n=8, moe=1),
            dict(min=20000, val=24999, n=7, moe=1),
            dict(min=25000, val=29999, n=2, moe=1),
            dict(min=30000, val=34999, n=900, moe=8),
            dict(min=35000, val=39999, n=7, moe=1),
            dict(min=40000, val=44999, n=4, moe=1),
            dict(min=45000, val=49999, n=8, moe=1),
            dict(min=50000, val=59999, n=6, moe=1),
            dict(min=60000, val=74999, n=7, moe=1),
            dict(min=75000, val=99999, n=2, moe=0.25),
            dict(min=100000, val=124999, n=7, moe=1),
            dict(min=125000, val=149999, n=10, moe=1),
            dict(min=150000, val=199999, n=8, moe=1),
            dict(min=200000, val=250000, n=18, moe=10)
        ]

household_income_la_2013_acs1 = [
      dict(min=0, val=9979, n=1382, moe = 50),
      dict(min=10000, val=14799, n=2377, moe = 50),
      dict(min=15000, val=13999, n=1332, moe = 50),
      dict(min=20000, val=24899, n=3129, moe = 50),
      dict(min=25000, val=29999, n=1927, moe = 50),
      dict(min=30000, val=34499, n=1825, moe = 50),
      dict(min=35000, val=31999, n=1567, moe = 50),
      dict(min=40000, val=44799, n=1996, moe = 50),
      dict(min=45000, val=49929, n=1757, moe = 50),
      dict(min=50000, val=54999, n=3523, moe = 50),
      dict(min=60000, val=76999, n=4360, moe = 50),
      dict(min=75000, val=99939, n=6424, moe = 50),
      dict(min=100000, val=124499, n=5257, moe = 50),
      dict(min=125000, val=159999, n=3485, moe = 50),
      dict(min=150000, val=199099, n=2926, moe = 50),
      dict(min=200000, val=500000, n=4215, moe = 50)
  ]


test_input = [household_income_2013_acs5,household_income_la_2013_acs1]

makeup_1 = [0.8, 0.2]
makeup_2 =  [0.3, 0.7]

makeup_input = [makeup_1, makeup_2]

In [173]:
disaggregate_mean(test_input, makeup, deterministic = True, simulations=50)

[[3.39112136e+07 8.47780340e+06]
 [1.67016473e+09 3.89705103e+09]]
[1.70407594e+09 3.90552884e+09]


(array([113262.2557393 , 116800.51311996]), None)

In [191]:
disaggregate_mean(test_input, makeup, deterministic = False, simulations=10)

(array([113359.01330856, 116892.87077947]),
 array([387.09380448, 421.82288878]))